// 🍞 TopicMaster 3000 - Topics & Categories
// The brain of the toaster!

export interface Topic {
  word: string;
  hint?: string; // Optional hint for kids mode
}

export interface Category {
  id: string;
  name: string;
  emoji: string;
  description: string;
  isKidsMode: boolean;
  color: string;
  timerSeconds: number;
  topics: Topic[];
}

export const CATEGORIES: Category[] = [
  // ========== REGULAR CATEGORIES ==========
  {
    id: "american-history",
    name: "American History",
    emoji: "🇺🇸",
    description: "From founding fathers to modern times",
    isKidsMode: false,
    color: "#3b82f6",
    timerSeconds: 30,
    topics: [
      { word: "The Boston Tea Party" },
      { word: "The Declaration of Independence" },
      { word: "Abraham Lincoln" },
      { word: "The Civil War" },
      { word: "The Louisiana Purchase" },
      { word: "The Revolutionary War" },
      { word: "George Washington" },
      { word: "The Constitution" },
      { word: "The Bill of Rights" },
      { word: "The Emancipation Proclamation" },
      { word: "Pearl Harbor" },
      { word: "The Moon Landing" },
      { word: "Martin Luther King Jr." },
      { word: "The Gold Rush" },
      { word: "The Oregon Trail" },
      { word: "Thomas Jefferson" },
      { word: "Benjamin Franklin" },
      { word: "The Alamo" },
      { word: "Manifest Destiny" },
      { word: "The New Deal" },
    ],
  },
  {
    id: "sat-words",
    name: "SAT Words",
    emoji: "📖",
    description: "Vocabulary that impresses",
    isKidsMode: false,
    color: "#8b5cf6",
    timerSeconds: 30,
    topics: [
      { word: "Ubiquitous" },
      { word: "Ephemeral" },
      { word: "Pragmatic" },
      { word: "Eloquent" },
      { word: "Ambiguous" },
      { word: "Benevolent" },
      { word: "Cacophony" },
      { word: "Diligent" },
      { word: "Empathy" },
      { word: "Frivolous" },
      { word: "Gregarious" },
      { word: "Hypothetical" },
      { word: "Inevitable" },
      { word: "Juxtaposition" },
      { word: "Meticulous" },
      { word: "Nostalgia" },
      { word: "Obstinate" },
      { word: "Paradox" },
      { word: "Resilient" },
      { word: "Serendipity" },
    ],
  },
  {
    id: "science",
    name: "Science & Nature",
    emoji: "🔬",
    description: "How the world works",
    isKidsMode: false,
    color: "#10b981",
    timerSeconds: 30,
    topics: [
      { word: "Photosynthesis" },
      { word: "Gravity" },
      { word: "Evolution" },
      { word: "The Water Cycle" },
      { word: "DNA" },
      { word: "Atoms" },
      { word: "Electricity" },
      { word: "Climate Change" },
      { word: "Black Holes" },
      { word: "The Scientific Method" },
      { word: "Magnetism" },
      { word: "Ecosystems" },
      { word: "Chemical Reactions" },
      { word: "The Big Bang" },
      { word: "Plate Tectonics" },
    ],
  },
  {
    id: "movies-tv",
    name: "Movies & TV",
    emoji: "🎬",
    description: "Lights, camera, explain!",
    isKidsMode: false,
    color: "#f59e0b",
    timerSeconds: 30,
    topics: [
      { word: "Star Wars" },
      { word: "The Godfather" },
      { word: "Jurassic Park" },
      { word: "The Office" },
      { word: "Breaking Bad" },
      { word: "Friends" },
      { word: "The Matrix" },
      { word: "Titanic" },
      { word: "Game of Thrones" },
      { word: "Forrest Gump" },
      { word: "The Avengers" },
      { word: "Stranger Things" },
      { word: "Harry Potter" },
      { word: "The Simpsons" },
      { word: "Back to the Future" },
    ],
  },
  {
    id: "food",
    name: "Food & Cooking",
    emoji: "🍳",
    description: "Delicious explanations",
    isKidsMode: false,
    color: "#ef4444",
    timerSeconds: 30,
    topics: [
      { word: "Sushi" },
      { word: "Thanksgiving Turkey" },
      { word: "Pizza" },
      { word: "Chocolate" },
      { word: "Sourdough Bread" },
      { word: "Tacos" },
      { word: "Ice Cream" },
      { word: "Pasta" },
      { word: "Barbecue" },
      { word: "Spaghetti" },
      { word: "Hamburgers" },
      { word: "Apple Pie" },
      { word: "Fried Chicken" },
      { word: "Cheese" },
      { word: "Coffee" },
    ],
  },
  {
    id: "technology",
    name: "Technology",
    emoji: "💻",
    description: "Digital world decoded",
    isKidsMode: false,
    color: "#6366f1",
    timerSeconds: 30,
    topics: [
      { word: "Artificial Intelligence" },
      { word: "The Internet" },
      { word: "Smartphones" },
      { word: "Social Media" },
      { word: "Virtual Reality" },
      { word: "Blockchain" },
      { word: "Cloud Computing" },
      { word: "WiFi" },
      { word: "Video Games" },
      { word: "Robots" },
      { word: "3D Printing" },
      { word: "GPS" },
      { word: "Streaming Services" },
      { word: "Electric Cars" },
      { word: "Drones" },
    ],
  },
  {
    id: "geography",
    name: "Geography",
    emoji: "🌍",
    description: "Around the world",
    isKidsMode: false,
    color: "#14b8a6",
    timerSeconds: 30,
    topics: [
      { word: "The Amazon Rainforest" },
      { word: "Mount Everest" },
      { word: "The Grand Canyon" },
      { word: "The Sahara Desert" },
      { word: "The Great Wall of China" },
      { word: "The Nile River" },
      { word: "Antarctica" },
      { word: "The Pacific Ocean" },
      { word: "Australia" },
      { word: "The Mediterranean Sea" },
      { word: "Volcanoes" },
      { word: "Islands" },
      { word: "The North Pole" },
      { word: "Rainforests" },
      { word: "The Eiffel Tower" },
    ],
  },
  {
    id: "music",
    name: "Music",
    emoji: "🎵",
    description: "Sounds and songs",
    isKidsMode: false,
    color: "#ec4899",
    timerSeconds: 30,
    topics: [
      { word: "The Beatles" },
      { word: "Rock and Roll" },
      { word: "Hip Hop" },
      { word: "Jazz" },
      { word: "Classical Music" },
      { word: "Elvis Presley" },
      { word: "Michael Jackson" },
      { word: "Taylor Swift" },
      { word: "Country Music" },
      { word: "The Guitar" },
      { word: "The Piano" },
      { word: "Concerts" },
      { word: "Music Videos" },
      { word: "Karaoke" },
      { word: "Drums" },
    ],
  },
  {
    id: "thanksgiving",
    name: "Thanksgiving",
    emoji: "🦃",
    description: "Gobble gobble!",
    isKidsMode: false,
    color: "#d97706",
    timerSeconds: 30,
    topics: [
      { word: "Turkey" },
      { word: "Pilgrims" },
      { word: "Gratitude" },
      { word: "Pumpkin Pie" },
      { word: "The Mayflower" },
      { word: "Cornucopia" },
      { word: "Stuffing" },
      { word: "Family Gatherings" },
      { word: "Macy's Parade" },
      { word: "Football" },
      { word: "Cranberry Sauce" },
      { word: "Plymouth Rock" },
      { word: "Native Americans" },
      { word: "Harvest" },
      { word: "Black Friday" },
    ],
  },

  // ========== KIDS CATEGORIES ==========
  {
    id: "dinosaurs",
    name: "Dinosaurs",
    emoji: "🦕",
    description: "Rawr! Ancient giants!",
    isKidsMode: true,
    color: "#22c55e",
    timerSeconds: 45,
    topics: [
      { word: "T-Rex", hint: "The king of dinosaurs with tiny arms!" },
      { word: "Triceratops", hint: "Has three horns on its head!" },
      { word: "Brontosaurus", hint: "Super long neck!" },
      { word: "Stegosaurus", hint: "Has plates on its back!" },
      { word: "Velociraptor", hint: "Small but super fast!" },
      { word: "Pterodactyl", hint: "A flying dinosaur!" },
      { word: "Fossils", hint: "Old bones in rocks!" },
      { word: "Dinosaur Eggs", hint: "Where baby dinos come from!" },
      { word: "Extinction", hint: "When dinosaurs went away!" },
      { word: "Herbivore", hint: "Eats only plants!" },
      { word: "Carnivore", hint: "Eats only meat!" },
      { word: "Jurassic", hint: "A time when dinos lived!" },
    ],
  },
  {
    id: "animals",
    name: "Animals",
    emoji: "🐾",
    description: "Furry, scaly, and feathery friends!",
    isKidsMode: true,
    color: "#f97316",
    timerSeconds: 45,
    topics: [
      { word: "Elephants", hint: "Big gray animal with a trunk!" },
      { word: "Lions", hint: "King of the jungle!" },
      { word: "Dolphins", hint: "Smart animals that swim!" },
      { word: "Penguins", hint: "Birds that can't fly but swim!" },
      { word: "Butterflies", hint: "Pretty bugs with colorful wings!" },
      { word: "Dogs", hint: "Man's best friend!" },
      { word: "Cats", hint: "Says meow!" },
      { word: "Giraffes", hint: "Super long neck!" },
      { word: "Monkeys", hint: "Loves bananas!" },
      { word: "Pandas", hint: "Black and white bears!" },
      { word: "Owls", hint: "Says hoo hoo at night!" },
      { word: "Sharks", hint: "Big fish with lots of teeth!" },
    ],
  },
  {
    id: "cartoons",
    name: "Cartoons",
    emoji: "📺",
    description: "Your favorite shows!",
    isKidsMode: true,
    color: "#a855f7",
    timerSeconds: 45,
    topics: [
      { word: "SpongeBob", hint: "Lives in a pineapple under the sea!" },
      { word: "Paw Patrol", hint: "Puppies that save the day!" },
      { word: "Frozen", hint: "Let it go!" },
      { word: "Mickey Mouse", hint: "Disney's famous mouse!" },
      { word: "Bluey", hint: "A blue dog from Australia!" },
      { word: "Peppa Pig", hint: "A pig who loves muddy puddles!" },
      { word: "Pokemon", hint: "Gotta catch 'em all!" },
      { word: "Mario", hint: "Red hat, loves mushrooms!" },
      { word: "Minecraft", hint: "Building with blocks!" },
      { word: "The Lion King", hint: "Hakuna Matata!" },
      { word: "Toy Story", hint: "Toys that come alive!" },
      { word: "Finding Nemo", hint: "A fish who got lost!" },
    ],
  },
  {
    id: "fairy-tales",
    name: "Fairy Tales",
    emoji: "🧙",
    description: "Once upon a time...",
    isKidsMode: true,
    color: "#ec4899",
    timerSeconds: 45,
    topics: [
      { word: "Cinderella", hint: "Lost her glass slipper!" },
      { word: "The Three Little Pigs", hint: "Huff and puff!" },
      { word: "Little Red Riding Hood", hint: "Visiting grandma!" },
      { word: "Goldilocks", hint: "This porridge is just right!" },
      { word: "Jack and the Beanstalk", hint: "A giant beanstalk!" },
      { word: "Snow White", hint: "Mirror mirror on the wall!" },
      { word: "The Ugly Duckling", hint: "Becomes a beautiful swan!" },
      { word: "Rapunzel", hint: "Let down your hair!" },
      { word: "Sleeping Beauty", hint: "Wakes up with a kiss!" },
      { word: "Hansel and Gretel", hint: "A house made of candy!" },
      { word: "Dragons", hint: "Breathes fire!" },
      { word: "Princesses", hint: "Lives in a castle!" },
    ],
  },
  {
    id: "space-kids",
    name: "Space",
    emoji: "🚀",
    description: "To infinity and beyond!",
    isKidsMode: true,
    color: "#3b82f6",
    timerSeconds: 45,
    topics: [
      { word: "The Moon", hint: "Shines at night!" },
      { word: "The Sun", hint: "A big bright star!" },
      { word: "Stars", hint: "Twinkle twinkle!" },
      { word: "Rockets", hint: "Goes zoom into space!" },
      { word: "Astronauts", hint: "People who go to space!" },
      { word: "Planets", hint: "Big balls in space!" },
      { word: "Mars", hint: "The red planet!" },
      { word: "Saturn", hint: "Has pretty rings!" },
      { word: "Aliens", hint: "Maybe from other planets!" },
      { word: "The Milky Way", hint: "Our galaxy!" },
      { word: "Shooting Stars", hint: "Make a wish!" },
      { word: "Telescopes", hint: "Helps you see far away!" },
    ],
  },
  {
    id: "superheroes",
    name: "Superheroes",
    emoji: "🦸",
    description: "Saving the day!",
    isKidsMode: true,
    color: "#ef4444",
    timerSeconds: 45,
    topics: [
      { word: "Spider-Man", hint: "Shoots webs!" },
      { word: "Batman", hint: "Has a cape and a cool car!" },
      { word: "Superman", hint: "Can fly and is super strong!" },
      { word: "Wonder Woman", hint: "Amazon princess!" },
      { word: "The Hulk", hint: "Big and green!" },
      { word: "Iron Man", hint: "Has a robot suit!" },
      { word: "Captain America", hint: "Has a shield!" },
      { word: "Thor", hint: "Has a magic hammer!" },
      { word: "Superpowers", hint: "Special abilities!" },
      { word: "Villains", hint: "The bad guys!" },
      { word: "Secret Identity", hint: "A hero's hidden name!" },
      { word: "Capes", hint: "Superheroes wear these!" },
    ],
  },
];

export function getCategory(id: string): Category | undefined {
  return CATEGORIES.find((c) => c.id === id);
}

export function getRandomTopic(category: Category): Topic {
  const index = Math.floor(Math.random() * category.topics.length);
  return category.topics[index];
}
